import {createContext,useContext,useState,useEffect} from 'react';
const LanguageContext=createContext(null);
const translations={
 en:{home:'Home',shop:'Shop',forYou:'For You',deals:'Deals',vendors:'Vendors',orders:'Orders',allCategories:'All Categories',search:'Search',signIn:'Sign in',becomeVendor:'Become a vendor',help:'Help & Support',shopNow:'Shop now',startSelling:'Start selling',viewAll:'View all',cart:'Cart',wishlist:'Wishlist',addToCart:'Add to cart',messages:'Messages'},
 rw:{home:'Ahabanza',shop:'Isoko',forYou:'Bikwiriye',deals:'Amasezerano',vendors:'Abacuruzi',orders:'Ibyatumijwe',allCategories:'Ibyiciro byose',search:'Shakisha',signIn:'Injira',becomeVendor:'Ba umucuruzi',help:'Ubufasha n’Inkunga',shopNow:'Gura ubu',startSelling:'Tangira gucuruza',viewAll:'Reba byose',cart:'Agaseke',wishlist:'Ibyifuzwa',addToCart:'Shyira mu gitebo',messages:'Ubutumwa'},
 fr:{home:'Accueil',shop:'Boutique',forYou:'Pour vous',deals:'Offres',vendors:'Vendeurs',orders:'Commandes',allCategories:'Toutes les catégories',search:'Rechercher',signIn:'Se connecter',becomeVendor:'Devenir vendeur',help:'Aide et support',shopNow:'Acheter',startSelling:'Commencer à vendre',viewAll:'Voir tout',cart:'Panier',wishlist:'Favoris',addToCart:'Ajouter au panier',messages:'Messages'}
};
const phraseTranslations={rw:{
'Home':'Ahabanza','Shop':'Isoko','For You':'Bikwiriye','Deals':'Amasezerano','Vendors':'Abacuruzi','Orders':'Ibyatumijwe','All Categories':'Ibyiciro byose','Search':'Shakisha','Sign in':'Injira','Become a vendor':'Ba umucuruzi','Help & Support':'Ubufasha n’Inkunga','Shop now':'Gura ubu','Start selling':'Tangira gucuruza','View all':'Reba byose','Cart':'Agaseke','Wishlist':'Ibyifuzwa','Add to cart':'Shyira mu gitebo','Messages':'Ubutumwa','Dashboard':'Imbonerahamwe','Analytics':'Isesengura','Payments':'Kwishyura','Reports':'Raporo','Settings':'Igenamiterere','Inventory':'Ububiko','Products':'Ibicuruzwa','Customers':'Abakiriya','Team / Staff':'Itsinda / Abakozi','Profile':'Umwirondoro','Wallet':'Umufuka w’amafaranga','Withdrawals':'Kubikuza','Earnings':'Amafaranga winjije','Conversions':'Abakiriya wazanwe','Delivery Tracking':'Gukurikirana itangwa','Delivery & Settlement':'Itangwa n’ishyurwa','Supplier Dashboard':'Dashboard','Affiliate Dashboard':'Dashboard','Seller Center':'Dashboard','My Store':'Ububiko bwanjye','Wholesale Products':'Ibicuruzwa byinshi','Vendor Orders':'Ibyatumijwe n’abacuruzi','Supply Requests':'Gusaba ibicuruzwa','Reviews':'Isuzuma','Fraud Protection':'Kurwanya uburiganya','Notifications':'Amatangazo','System Administration':'Imicungire ya sisitemu','Financial Ledger':'Igitabo cy’imari','Commission Rules':'Amategeko ya komisiyo','Trust Scores':'Amanota y’icyizere','Disputes':'Amakimbirane','Refunds':'Gusubizwa amafaranga','Advertising':'Kwamamaza','Subscriptions':'Kwiyandikisha','Recommendations':'Ibyifuzo','Supplier Matching':'Guhuza abatanga n’abacuruzi','Languages':'Indimi','Locations':'Ahantu','Security':'Umutekano','Audit Logs':'Amateka y’ibikorwa','View marketplace':'Reba isoko','Sign out':'Sohoka','Save':'Bika','Cancel':'Hagarika','Delete':'Siba','Edit':'Hindura','View':'Reba','Send':'Ohereza','Add':'Ongeraho','Filter':'Shungura','Today':'Uyu munsi','7 Days':'Iminsi 7','30 Days':'Iminsi 30','3 Months':'Amezi 3','6 Months':'Amezi 6','1 Year':'Umwaka 1','In stock':'Kirahari','On sale':'Ku giciro cyagabanyijwe','New arrivals':'Ibishya','Featured':'Ibyatoranyijwe','Top rated':'Bifite amanota menshi','No products found':'Nta bicuruzwa bibonetse','No records found.':'Nta makuru yabonetse','Available balance':'Amafaranga ahari','Pending commission':'Komisiyo itegerejwe','Minimum withdrawal':'Umubare muto wo kubikuza','Request withdrawal':'Saba kubikuza','Payment method':'Uburyo bwo kwishyura','Account / phone':'Konti / telefoni','Full name':'Amazina yose','Phone number':'Nimero ya telefoni','Email':'Imeyili','Description':'Ibisobanuro','Category':'Icyiciro','Price':'Igiciro','Stock':'Ububiko','Status':'Imiterere','Amount':'Amafaranga','Date':'Itariki','Actions':'Ibikorwa','Welcome to MVEC':'Murakaza neza kuri MVEC','Rwanda’s multi-vendor marketplace':'Isoko rya MVEC ry’abacuruzi benshi mu Rwanda'},
fr:{'Home':'Accueil','Shop':'Boutique','For You':'Pour vous','Deals':'Offres','Vendors':'Vendeurs','Orders':'Commandes','All Categories':'Toutes les catégories','Search':'Rechercher','Sign in':'Se connecter','Become a vendor':'Devenir vendeur','Help & Support':'Aide et support','Shop now':'Acheter','Start selling':'Commencer à vendre','View all':'Voir tout','Cart':'Panier','Wishlist':'Favoris','Add to cart':'Ajouter au panier','Messages':'Messages','Dashboard':'Tableau de bord','Analytics':'Analyses','Payments':'Paiements','Reports':'Rapports','Settings':'Paramètres','Inventory':'Stock','Products':'Produits','Customers':'Clients','Team / Staff':'Équipe / personnel','Profile':'Profil','Wallet':'Portefeuille','Withdrawals':'Retraits','Earnings':'Gains','Conversions':'Conversions','Delivery Tracking':'Suivi des livraisons','Delivery & Settlement':'Livraison et règlement','Reviews':'Avis','Notifications':'Notifications','Refunds':'Remboursements','Advertising':'Publicité','Languages':'Langues','Locations':'Emplacements','Security':'Sécurité','View marketplace':'Voir la marketplace','Sign out':'Se déconnecter','Save':'Enregistrer','Cancel':'Annuler','Delete':'Supprimer','Edit':'Modifier','View':'Voir','Send':'Envoyer','Add':'Ajouter','Filter':'Filtrer','Today':'Aujourd’hui','7 Days':'7 jours','30 Days':'30 jours','3 Months':'3 mois','6 Months':'6 mois','1 Year':'1 an','In stock':'En stock','On sale':'En promotion','New arrivals':'Nouveautés','Featured':'En vedette','Top rated':'Mieux notés','No products found':'Aucun produit trouvé','No records found.':'Aucun enregistrement','Available balance':'Solde disponible','Pending commission':'Commission en attente','Minimum withdrawal':'Retrait minimum','Request withdrawal':'Demander un retrait','Payment method':'Mode de paiement','Account / phone':'Compte / téléphone','Full name':'Nom complet','Phone number':'Numéro de téléphone','Email':'E-mail','Description':'Description','Category':'Catégorie','Price':'Prix','Stock':'Stock','Status':'Statut','Amount':'Montant','Date':'Date','Actions':'Actions'}};
export function LanguageProvider({children}){
 const [language,setLanguageState]=useState(()=>localStorage.getItem('mvec_language')||'rw');
 const [custom,setCustom]=useState(()=>{try{return JSON.parse(localStorage.getItem('mvec_translations')||'{}')}catch{return{}}});
 const setLanguage=l=>{localStorage.setItem('mvec_language',l);setLanguageState(l)};
 const t=k=>custom[language]?.[k]||translations[language]?.[k]||custom.en?.[k]||translations.en[k]||k;
 const updateTranslation=(lang,key,value)=>{const next={...custom,[lang]:{...(custom[lang]||{}),[key]:value}};localStorage.setItem('mvec_translations',JSON.stringify(next));setCustom(next)};
 useEffect(()=>{const apply=()=>{const dict=phraseTranslations[language]||{};const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(!n.nodeValue.trim()||n.parentElement?.closest('script,style,noscript'))continue;const original=n.__mvecOriginal||n.nodeValue;n.__mvecOriginal=original;const key=original.trim();if(language==='en')n.nodeValue=original;else if(dict[key])n.nodeValue=original.replace(key,dict[key]);}};apply();const observer=new MutationObserver(apply);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[language]);
 return <LanguageContext.Provider value={{language,setLanguage,t,translations,custom,updateTranslation}}>{children}</LanguageContext.Provider>
}
export function useLanguage(){const c=useContext(LanguageContext);if(!c)throw new Error('useLanguage must be used within LanguageProvider');return c;}
